packages:
  - packages/*
  - playground
  - docs
  - docs/internal/*
  - internal/*
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@hello-lizhihua/element-plus@0.1.2 || 0.1.3'
